name: Deployment Pipeline
on: [workflow_dispatch]
jobs:
  staging:
    name: Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: remote into the ssh production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/bw-website-staging
          git pull --rebase
          rm -rf node_modules
          nvm use 22
          npm install
          npm run build
  production:
    name: Production
    runs-on: ubuntu-latest
    depends-on: staging
    environment: production
    steps:
    - name: remote into the ssh production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/bw-website
          rm -rf node_modules
          git pull --rebase
          nvm use 22
          npm install
          npm run build
